import type { GlobalSettings } from './types'

export const DEFAULT_GLOBAL_SETTINGS: GlobalSettings = {
  id: 0,
  documentId: 'default-global-settings',
  site_name: 'SteinbergValentino Group',
  tagline: 'The Best IR Firm For Small & Mid-Cap Businesses',
  footer_blurb:
    'The premier investor relations firm for small and mid-cap public companies.',
  contact_phone: '(646) 535-3995',
  contact_email: 'contact@steinbergvalentino.com',
  address: '100 Church Street, Suite 8010, Manhattan, New York 10007',
  footer_copyright: `© ${new Date().getFullYear()} SteinbergValentino Group. All rights reserved.`,
  primary_navigation: [
    { label: 'Home', href: '/' },
    {
      label: 'About',
      href: '/about',
      children: [
        { label: 'How It Works', href: '/how-it-works' },
        { label: 'About Us', href: '/about' },
        { label: 'Capabilities', href: '/capabilities' },
        { label: 'Industry Expertise', href: '/industry-expertise' },
        { label: 'Financial Marketing', href: '/services/financial-marketing' },
      ],
    },
    {
      label: 'Advisory',
      href: '/services/advisory',
      children: [
        { label: 'Strategic Advisory', href: '/services/strategic-advisory' },
        { label: 'Strategic Communications', href: '/services/strategic-communications' },
        { label: 'Transactional Advisory', href: '/services/transactional-advisory' },
        { label: 'Capital Formation', href: '/services/capital-formation' },
        { label: 'Crises Management', href: '/services/crises-management' },
        { label: 'Litigation Communications', href: '/services/litigation-communications' },
      ],
    },
    {
      label: 'Market Entry',
      href: '/services/market-entry',
      children: [
        { label: 'Media Relations', href: '/services/media-relations' },
        { label: 'Media Strategy', href: '/services/media-strategy' },
        { label: 'Multicultural Engagement', href: '/services/multicultural-engagement' },
      ],
    },
    {
      label: 'Exchanges',
      href: '/exchanges/otc-markets',
      children: [
        { label: 'NASDAQ Small Cap', href: '/exchanges/nasdaq-small-cap' },
        { label: 'OTC Markets', href: '/exchanges/otc-markets' },
        { label: 'Canadian TSX', href: '/exchanges/canadian-tsx' },
        { label: 'Canadian CSE', href: '/exchanges/canadian-cse' },
        { label: 'German Frankfurt', href: '/exchanges/german-frankfurt' },
      ],
    },
  ],
  footer_quick_links: [
    { label: 'Home', href: '/' },
    { label: 'How It Works', href: '/how-it-works' },
    { label: 'About Us', href: '/about' },
    { label: 'Capabilities', href: '/capabilities' },
    { label: 'Industry Expertise', href: '/industry-expertise' },
    { label: 'Contact Us', href: '/contact' },
    { label: 'Sitemap', href: '/sitemap' },
  ],
  footer_service_links: [
    { label: 'Advisory', href: '/services/advisory' },
    { label: 'Strategic Advisory', href: '/services/strategic-advisory' },
    { label: 'Strategic Communications', href: '/services/strategic-communications' },
    { label: 'Transactional Advisory', href: '/services/transactional-advisory' },
    { label: 'Capital Formation', href: '/services/capital-formation' },
    { label: 'Crises Management', href: '/services/crises-management' },
    { label: 'Market Entry', href: '/services/market-entry' },
    { label: 'Media Relations', href: '/services/media-relations' },
    { label: 'Media Strategy', href: '/services/media-strategy' },
    { label: 'Multicultural Engagement', href: '/services/multicultural-engagement' },
    { label: 'Financial Marketing', href: '/services/financial-marketing' },
    { label: 'Litigation Communications', href: '/services/litigation-communications' },
  ],
  footer_exchange_links: [
    { label: 'NASDAQ Small Cap', href: '/exchanges/nasdaq-small-cap' },
    { label: 'OTC Markets', href: '/exchanges/otc-markets' },
    { label: 'Canadian TSX', href: '/exchanges/canadian-tsx' },
    { label: 'Canadian CSE', href: '/exchanges/canadian-cse' },
    { label: 'German Frankfurt', href: '/exchanges/german-frankfurt' },
  ],
  footer_legal_links: [],
  sitemap_heading: 'Sitemap',
  sitemap_intro:
    'A complete index of all pages on the SteinbergValentino Group website.',
  sitemap_meta_title: 'Sitemap | SteinbergValentino Group',
  sitemap_meta_description:
    'Browse the full SteinbergValentino site structure, including firm pages, services, and exchange support pages.',
  search_placeholder: 'Search services, exchanges, and insights…',
  search_heading: 'Search',
  search_meta_title: 'Search | SteinbergValentino Group',
  search_meta_description:
    'Search across SteinbergValentino Group services, exchange coverage, and firm pages.',
  social_facebook:  'https://www.facebook.com/SteinbergValentinoGroup/',
  social_twitter:   'https://twitter.com/SV__Group',
  social_instagram: 'https://www.instagram.com/steinbergvalentinogroup',
  social_linkedin:  'https://www.linkedin.com/company/steinberg-valentino-group/',
  social_pinterest: 'https://www.pinterest.com/SteinbergValentinoGroup',
  /* ── UI microcopy (offline fallback; live values come from Strapi) ── */
  nav_cta_label: 'Contact Us',
  footer_contact_heading: 'Get in Touch',
  footer_email_label: 'Email',
  footer_phone_label: 'Phone',
  footer_office_label: 'Office',
  footer_firm_heading: 'Quick Links',
  footer_services_heading: 'Social',
  footer_exchanges_heading: 'Exchanges',
  faq_eyebrow: 'FAQ',
  faq_title: 'Frequently Asked Questions',
  search_eyebrow: 'Site Search',
  search_button_label: 'Search',
  search_empty_text: 'Enter a term above to search across our services, exchanges, and firm pages.',
  search_type_page: 'Page',
  search_type_service: 'Service',
  search_type_exchange: 'Exchange',
  search_results_singular: 'result',
  search_results_plural: 'results',
  form_first_name_label: 'First Name',
  form_last_name_label: 'Last Name',
  form_email_label: 'Email',
  form_message_label: 'Message',
  form_submit_label: 'Submit',
  form_submitting_label: 'Sending...',
  form_success_heading: 'Thank you',
  form_success_body: 'Your message has been received.',
  label_read_more: 'Read More',
  label_all_services: 'All Services',
  label_view_details: 'View details →',
  service_overview_eyebrow: 'What We Do',
  service_overview_band_eyebrow: 'Overview',
  service_engage_heading: 'Interested in {service}?',
  service_engage_body:
    "Speak with our team to learn how this service can be tailored to your company's needs and objectives.",
  service_engage_cta_label: 'Contact Us',
  service_back_label: '← All Services',
  service_approach_title: 'Our Approach',
  service_cta_eyebrow: 'Next Step',
  service_cta_heading: 'Ready to put {service} to work for your company?',
  service_cta_label: 'Contact Our Team',
  service_news_eyebrow: 'News & Insights',
  service_news_heading: 'Updates from {service}',
  service_news_cta_label: 'Read More',
  exchange_hero_eyebrow: 'Exchange Support',
  exchange_breadcrumb_label: 'Market Entry',
  exchange_approach_title: 'Our Approach',
  exchange_keyfacts_eyebrow: 'Key Facts',
  exchange_cta_eyebrow: 'Ready to List?',
  exchange_cta_heading: 'Let us guide your {exchange} listing journey.',
  exchange_cta_label: 'Contact the Firm',
  service_breadcrumb_label: 'Services',
  sitemap_eyebrow: 'Site Index',
  sitemap_firm_heading: 'The Firm',
  sitemap_services_heading: 'Services',
  sitemap_exchanges_heading: 'Exchanges',
}
